name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.3.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.1
  google_maps_flutter: ^2.14.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
